language: ruby

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - ruby-head

before_install:
  - echo "Updating Bundler to ~> 1.9 until TravisCI has upgraded."
  - gem install bundler -v "~> 1.9"
  - bundle --version

bundler_args: --without guard

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  code_climate:
    repo_token:
      secure: "WSrIaJVtAh88T7cd3DQY38yxiDz44Oms4Z5Dm+mVUv8gpKWixMR3t5ShmDW8+XXWWj3s3WUa2t5yZugrfz0gkrKCxSII6VURakBKy2jEKnEnJWoh8LKYjXHYW2fOU/PpclSFl0Ynxvt8Nn/F9dpbaGAqj2DwycAV4EtByuy06X0="
